config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/test-project:
      branch: main
      credential_tmp: true
      repo: https://gitlab.a.incd.pt/jprm/test-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/test-project git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-auburn-cichlid.sh
        container: qc.acc_crappy-maroon-sparrow
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/test-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-bronze-booby.sh
        container: qc.doc_foggy-magenta-slug
      gitlab.a.incd.pt/jprm/test-project git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-taupe-toucan.sh
        container: qc.doc_stealthy-emerald-crocodile
      gitlab.a.incd.pt/jprm/test-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-gamboge-turkey.sh
        container: qc.doc_stinky-gamboge-mayfly
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/test-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-firebrick-slug.sh
        container: qc.lic_squirrely-cinnabar-cow
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/test-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-amaranth-discus.sh
        container: qc.sec_droopy-mauve-centipede
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/test-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-seashell-russel.sh
        container: qc.sty_baggy-cerise-oyster
      gitlab.a.incd.pt/jprm/test-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-khaki-fowl.sh
        container: qc.sty_skanky-periwinkle-maltese
      gitlab.a.incd.pt/jprm/test-project jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-xanthic-eagle.sh
        container: qc.sty_cozy-sepia-hummingbird
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/test-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-amber-flounder.sh
        container: qc.uni_freaky-yellow-raccoon
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/test-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-ecru-dane.sh
        container: qc.ver_surly-periwinkle-dollar
timeout: 5400
