config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/test-project:
      branch: main
      credential_tmp: true
      repo: https://gitlab.a.incd.pt/jprm/test-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/test-project git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-cinnabar-mastiff.sh
        container: qc.acc_cheeky-scarlet-capuchin
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/test-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-malachite-bee.sh
        container: qc.doc_snazzy-maroon-worm
      gitlab.a.incd.pt/jprm/test-project git:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-cerulean-terrier.sh
        container: qc.doc_silly-cinnamon-cow
      gitlab.a.incd.pt/jprm/test-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-white-tarantula.sh
        container: qc.doc_skanky-charcoal-reindeer
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/test-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-cream-fousek.sh
        container: qc.lic_trippy-apricot-yak
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/test-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-ruby-lion.sh
        container: qc.sec_paltry-black-shrimp
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/test-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-aqua-fly.sh
        container: qc.sty_slimy-magnolia-echidna
      gitlab.a.incd.pt/jprm/test-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-salmon-balinese.sh
        container: qc.sty_baggy-persimmon-chinook
      gitlab.a.incd.pt/jprm/test-project jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-myrtle-anteater.sh
        container: qc.sty_thirsty-indigo-lemur
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/test-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-aqua-lemur.sh
        container: qc.uni_homely-violet-alligator
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/test-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-burgundy-serval.sh
        container: qc.ver_gloppy-zucchini-kingfisher
timeout: 5400
