config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.a.incd.pt/jprm/test-project:
      branch: main
      credential_tmp: true
      repo: https://gitlab.a.incd.pt/jprm/test-project.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.a.incd.pt/jprm/test-project git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-rust-wrasse.sh
        container: qc.acc_surly-lavender-ant
  QC.Doc:
    repos:
      gitlab.a.incd.pt/jprm/test-project find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-auburn-bloodhound.sh
        container: qc.doc_homey-coral-kangaroo
      gitlab.a.incd.pt/jprm/test-project git:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cerise-dollar.sh
        container: qc.doc_grumpy-crimson-turkey
      gitlab.a.incd.pt/jprm/test-project markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-wisteria-buzzard.sh
        container: qc.doc_stealthy-sapphire-newt
  QC.Lic:
    repos:
      gitlab.a.incd.pt/jprm/test-project licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-olivine-fossa.sh
        container: qc.lic_cozy-razzmatazz-audemer
  QC.Sec:
    repos:
      gitlab.a.incd.pt/jprm/test-project bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cinnamon-donkey.sh
        container: qc.sec_seedy-chartreuse-bison
  QC.Sty:
    repos:
      gitlab.a.incd.pt/jprm/test-project flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-ivory-dugong.sh
        container: qc.sty_greasy-flax-emu
      gitlab.a.incd.pt/jprm/test-project hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-ochre-earwig.sh
        container: qc.sty_nerdy-lemon-wombat
      gitlab.a.incd.pt/jprm/test-project jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-aqua-bonobo.sh
        container: qc.sty_baggy-asparagus-turtle
  QC.Uni:
    repos:
      gitlab.a.incd.pt/jprm/test-project pytest:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-cream-bongo.sh
        container: qc.uni_stuffy-periwinkle-dog
  QC.Ver:
    repos:
      gitlab.a.incd.pt/jprm/test-project get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-magenta-goose.sh
        container: qc.ver_lumpy-cream-mayfly
timeout: 5400
